<a href="https://colab.research.google.com/github/adachao/EECE5510/blob/master/intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=1
type(a)

int

In [ ]:
a = 1.0
type(a)

float

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
i = 0
while (i < 10):
   print(i) 
   i += 1 

0
1
2
3
4
5
6
7
8
9


In [ ]:
name_list = ['Henry', 'Reza', 'Mary']
print(name_list)

['Henry', 'Reza', 'Mary']


In [ ]:
numbers_list = [1,2,3]
print(numbers_list)

[1, 2, 3]


In [ ]:
type(numbers_list)

list

In [ ]:
mixed_list = ['Henry', 1, 1.3333]
print(mixed_list)

['Henry', 1, 1.3333]


In [ ]:
numbers_list.append(5)
print(numbers_list)


['Henry', 2, 3, 5, 5, 5, 5]


In [ ]:
numbers_list[0] = 'Henry'
print(numbers_list)

['Henry', 2, 3, 5, 5, 5, 5]


In [ ]:
print(numbers_list[1])


2


In [ ]:
name_dict = {'Henry':220, 'Reza':450, 'Mary':328}
print(name_dict)
print(name_dict['Mary'])
print("Henry's extension is " + str(name_dict['Henry']) )

{'Henry': 220, 'Reza': 450, 'Mary': 328}
328
Henry's extension is 220


In [ ]:
numbers_dict = {1 : 'Henry', 2:'Reza', 3:'Mary'}
print(numbers_dict[1])

Henry


In [ ]:
name_tuple = ('Henry', 'Hugh', 'Barbra')
print(name_tuple[0:2])

('Henry', 'Hugh')


In [ ]:
numbers_tuple = (1, 2, 3)
print(numbers_tuple)

(1, 2, 3)


In [ ]:
name_set = {'Henry', 'Reza', 'Mary', 'Henry'}
print(name_set)

{'Mary', 'Henry', 'Reza'}


In [ ]:
name_set = name_set.union({'JOhn', 'Susan'})
print(name_set)

{'Mary', 'Henry', 'Reza', 'JOhn', 'Susan'}


In [ ]:
name_tuple[0] = John 

NameError: ignored

In [ ]:
fo = open('sample_data/anacombe.json')
for i in fo.readlines():
print(i)

IndentationError: ignored

In [ ]:
other_name_set = {'John', 'Susan'}
all_name_set = name_set.union(other_name_set)
print(all_name_set)

{'Mary', 'Henry', 'Reza', 'John', 'JOhn', 'Susan'}


In [7]:
a = [[1, 2, 3], [4, 5, 6], [6, 7, 8]] 
print(a[0][0])

1


In [14]:
list = ['Minneapolis','MN','USA']
print(list)
','. join(list)

['Minneapolis', 'MN', 'USA']


'Minneapolis,MN,USA'

In [12]:
a = [1,2,3,4,2,3,5] 
b= [i for i in a if i > 2]
print(b) 

[3, 4, 3, 5]


In [15]:
a = [1,2,3,4,2,3,5] 
b = [] 
for i in a: 
  if i>2: 
    b.append(i) 
    print(b) 

[3]
[3, 4]
[3, 4, 3]
[3, 4, 3, 5]


In [13]:
import numpy as np
a= np.random.rand(5, 5)
a


array([[0.522157  , 0.31558843, 0.15426114, 0.8084386 , 0.23292433],
       [0.6276085 , 0.86721474, 0.10609556, 0.74677439, 0.06650358],
       [0.18123951, 0.22095721, 0.09120531, 0.21156486, 0.81731363],
       [0.05868217, 0.77499923, 0.412023  , 0.50628796, 0.73249141],
       [0.98524729, 0.71631291, 0.71614071, 0.67249823, 0.85984957]])

In [18]:
transpose = np.transpose(a)
print(transpose)

[[0.522157   0.6276085  0.18123951 0.05868217 0.98524729]
 [0.31558843 0.86721474 0.22095721 0.77499923 0.71631291]
 [0.15426114 0.10609556 0.09120531 0.412023   0.71614071]
 [0.8084386  0.74677439 0.21156486 0.50628796 0.67249823]
 [0.23292433 0.06650358 0.81731363 0.73249141 0.85984957]]


In [19]:
a.T

array([[0.522157  , 0.6276085 , 0.18123951, 0.05868217, 0.98524729],
       [0.31558843, 0.86721474, 0.22095721, 0.77499923, 0.71631291],
       [0.15426114, 0.10609556, 0.09120531, 0.412023  , 0.71614071],
       [0.8084386 , 0.74677439, 0.21156486, 0.50628796, 0.67249823],
       [0.23292433, 0.06650358, 0.81731363, 0.73249141, 0.85984957]])

In [17]:
Inverse = np.linalg.inv(a)
print(Inverse)

[[-0.57120166  0.74889979  0.61974479 -1.53840805  0.81826762]
 [-1.45743242  1.39895933  0.06918402  0.44465528 -0.15795268]
 [ 0.32156877 -1.56066106 -2.24785085  1.17757904  1.16708897]
 [ 2.13284894 -0.67577866 -0.4086499   0.61546274 -0.66136773]
 [-0.06730605 -0.19518676  1.42401019 -0.06979111 -0.09778887]]


AttributeError: ignored

In [5]:
import cv2
!wget 'https://github.com/Henry-Medeiros/images/raw/master/Marquette.jpg'
image = cv2.imread("Marquette.jpg")
rows,cols,

--2021-09-13 19:12:12--  https://github.com/Henry-Medeiros/images/raw/master/Marquette.jpg
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Henry-Medeiros/images/master/Marquette.jpg [following]
--2021-09-13 19:12:12--  https://raw.githubusercontent.com/Henry-Medeiros/images/master/Marquette.jpg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 482326 (471K) [image/jpeg]
Saving to: ‘Marquette.jpg.1’

Marquette.jpg.1     100%[===================>] 471.02K  --.-KB/s    in 0.005s  

2021-09-13 19:12:12 (93.3 MB/s) - ‘Marquette.jpg.1’ saved [482326/482326]



In [9]:
h, w = image.shape[:2]

print("Height = {},  Width = {}".format(h, w))
(B, G, R) = image[100, 100]
print("R = {}, G = {}, B = {}".format(R, G, B))
B = image[100, 100, 0]
print("B = {}".format(B))


Height = 500,  Width = 700
R = 35, G = 57, B = 36
B = 36


In [10]:
roi = image[100 : 500, 200 : 700]
resize = cv2.resize(image, (800, 800))